# Device Settings
#
# Configure your sensors below. Configuration is simply done by adding them to this list.
#
# mac:          (required) MAC Address of the bluetooth LT Thermometer
# custom_name:  (optional) to override the name provided by bluetooth
# domoticz_idx: (optional) id of the virtual sensor to be updated through domoticz
devices:
  -
    mac: C8:33:DE:43:2C:00
    custom_name: LT Bureau
    domoticz_idx: 96
  -
    mac: C8:33:DE:43:2C:01
    custom_name: LT Bureau (14)
    domoticz_idx: 39

# Logging
# log_level: Information to log  ERROR|WARNING|NOTICE|INFO|DEBUG    Defaults to INFO
logging:
  log_level: INFO

# MQTT Settings
mqtt:
  enable: true                        # Enable MQTT. Publish MQTT messages or just print output. Default: True
  host: 127.0.0.1                     # MQTT broker address (defaults to 127.0.0.1)
  port: 1883                          # Defaults to 1883
  username: username                  # Username for MQTT server ('username' if not required)
  password: none                      # Password for MQTT (None if not required)
  prefix: lt_temp/                    # MQTT Topic Prefix.
  discovery: true                     # Home Assistant Discovery (true/false), defaults to true
  discovery_prefix: homeassistant/    # Home Assistant Discovery Prefix, defaults to homeassistant/
